[build]
  base = "frontend"
  publish = "build"          # <-- was "frontend/build"; remove the extra "frontend"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
